# Nome da aplicacao Spring Boot 
spring.application.name=chamapro

# Configuracao do banco Postgres
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.profiles.active=dev

# Configuracao do JPA
spring.jpa.hibernate.ddl-auto=update     

# Configuracoes de exibicao de SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=truel

jwt.secret=chamapro-chave-secreta-super-segura-para-jwt-2026-cefet-mg-projeto-funciona-porfavor
jwt.expiration=86400000

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true